default:
  script: "trouble_brewing"
  townsfolk_count: 7
  outsider_count: 0
  minion_count: 1
  max_rounds: 6
  random_seed: null
  model: "claude-3-5-haiku-20241022"

small_game:
  script: "trouble_brewing"
  townsfolk_count: 5
  outsider_count: 1
  minion_count: 1
  max_rounds: 6
  random_seed: null
  model: "claude-3-5-haiku-20241022"

large_game:
  script: "trouble_brewing"
  townsfolk_count: 9
  outsider_count: 2
  minion_count: 2
  max_rounds: 8
  random_seed: null
  model: "claude-3-5-haiku-20241022"

test_game:
  script: "trouble_brewing"
  townsfolk_count: 3
  outsider_count: 0
  minion_count: 1
  max_rounds: 4
  random_seed: 42
  model: "claude-3-5-haiku-20241022" 